### ISSUE TITLE
[v2] Automating regeneration of Info file

### ISSUE THREAD

**Issue by jvdydev** [SystemCrafters/crafted-emacs#379]
From time to time, we get merge conflicts because two PRs change documentation, which results in both regenerating the info file (thus leading to a merge issue).
It also has happened that regeneration was forgotten.

Therefor, we want to move the building of the info file into CI.
I threw together a small workflow, however I first want to give anyone interested the chance to discuss (improvements, optimizations, ...).

The current workflow (branch set to `craftedv2RC1`, eventually this would become `master`):
```yml
name: regenerate-info

on:
  push:
    paths:
      - docs/*.org
    branches:
      - craftedv2RC1

jobs:
  regenerate-info:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Generate info
      working-directory: ./docs
      run: make

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Regenerate info file
```

This would rebuild the info file if any org file in the `docs` directory changed.
The newly built info file would then be committed by the last committer (co-authored by gihub-actions bot).

Discussion welcome :smile:

**Comment by sthesing** [comment]
Looks good to me, too! Thanks for digging into this.

**Comment by jvdydev** [comment]
So after I *thought* I had fixed the issue (from `push` to `pull_request` + a check if it's closed), apparently that is ran *after* the PR has been merged and pushes onto the "to-merge" branch.

Meaning the target branch doesn't get the updated info buffer, but the source branch of the merge does ... *after* the merge.

I'll look into this more and see if there is an "before merging" or something

**Comment by jvdydev** [comment]
After some more research, it seems there is no way to push to the target branch on PR.

We could simply run the action on the "main" branch (currently `craftedv2RC1`), there is only really PR merges going there.
Even if one of us pushes to main directly, that also would trigger the action which is probably what we would want in that situation anyway.

However, if someone forks, they have to create a new branch before committing (e.g. to make a PR), otherwise the Action will trigger for them.
Although arguably, people shouldn't push to `craftedv2RC1`/`master` on their fork either.

Thoughts?

**Comment by jeffbowman** [comment]
> However, if someone forks, they have to create a new branch before committing (e.g. to make a PR), otherwise the Action will trigger for them.

Umm... That's interesting.  So forking this repo will get all the "extras" like this (and possibly linting in the future)... that's sorta unfortunate.  I'd like to see that stuff here, but I'm not sure I want to inflict it on someone who forks the repo.

**Comment by jvdydev** [comment]
The last resort could also be to manually run the Action, however it somewhat defeats the point of having the action (except for ensuring a cleanly built info file, but the Makefile already does that) ...

People can remove the `.github` directory in their fork, would remove the actions (and bug templates etc.).
I guess they are passed down to forks as they are part of the git-versioned files.
Maybe there are some more conditional flags for running the Action, I'll look a little more into that.

**Comment by jvdydev** [comment]
Some more experimentation later, it seems I found the solution.
The following will run an action *after* the merge, build the docs, then push a commit *to* main with the updated info buffer (if the PR was merged and `docs/*.org` changed).

(I used `main` here, replace that in your head with whatever branch we want to run this on)
```yml
name: regenerate-info

on:
  pull_request:
    types:
      - closed
    paths:
      - docs/*.org
    branches:
      - main

jobs:
  regenerate-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Generate info
      working-directory: ./docs
      run: make

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # This basically says "push to main"
        branch: main
        commit_message: Regenerate info buffer


```
